<?php
/**
 * Notice: Install htslib and bcftools package before use this module.
 */
require_once 'includes/zmap_genotype.form.inc';
require_once 'api/zmap_genotype.api.inc';

/**
 * Implements hook_menu.
 */
function zmap_genotype_menu()
{
    $items['zmap_genotype/result/genotype/dataset/%'] = array(
        'title' => 'ZEAMAP Genotype Search',
        'page callback' => 'zmap_genotype_search_result',
        'page arguments' => array(4, 6, 8, 10, 12),
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
    );

    $items['zmap_genotype/search'] = array(
        'title' => 'Zeamap Genotype Search',
        'page callback' => 'zmap_genotype_search',
        'access arguments' => array('access content'),
        'type' => MENU_NORMAL_ITEM,
    );

    $items['api/genotype/retrive_germplasm/dataset/%'] = array(
        'page callback' => 'zmap_genotype_api_retrive_germplasm',
        'page arguments' => array(4),
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );

    $items['api/genotype/result/dataset/%'] = array(
        'page callback' => 'zmap_genotype_api_retrive_genotype_search_result',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );

    return $items;
}

function zmap_genotype_search()
{
    $path = drupal_get_path('module', 'zmap_genotype');

    drupal_add_css($path.'/theme/css/zTreeStyle.css', array('group' => CSS_DEFAULT, 'every_page' => false));
    drupal_add_css($path.'/theme/css/zmap_genotype_search_form.css', array('group' => CSS_DEFAULT, 'every_page' => false));

    drupal_add_js($path.'/theme/js/jquery-3.2.1.min.js');
    drupal_add_js($path.'/theme/js/ext/jquery.ztree.core.js');
    drupal_add_js($path.'/theme/js/ext/jquery.ztree.excheck.js');
    drupal_add_js($path.'/theme/js/ext/jquery.ztree.exedit.js');
    drupal_add_js($path.'/theme/js/ext/jquery.ztree.exhide.js');
    drupal_add_js($path.'/theme/js/ext/fuzzysearch.js');
    drupal_add_js($path.'/theme/js/zmap_genotype_form.js');

    return theme('zmap_genotype_search');
}

function zmap_genotype_search_result($dataset, $germplasms, $chr, $start, $end)
{
    $path = drupal_get_path('module', 'zmap_genotype');
	//add css
	drupal_add_css($path.'/theme/css/tabulator.min.css', array('group' => CSS_DEFAULT, 'every_page' => false));
    drupal_add_css($path.'/theme/css/zTreeStyle.css', array('group' => CSS_DEFAULT, 'every_page' => false));
    drupal_add_css($path.'/theme/css/zmap_genotype_search_form.css', array('group' => CSS_DEFAULT, 'every_page' => false));
    drupal_add_css($path.'/theme/css/zmap_genotype_search_result.css', array('group' => CSS_DEFAULT, 'every_page' => false));

    //add js
    drupal_add_js(array('zmap_genotype' => array('dataset' => $dataset, 'germplasms' => $germplasms, 'chr' => $chr, 'start' => $start, 'end' => $end)), 'setting');
    drupal_add_js($path.'/theme/js/jquery-3.2.1.min.js');
    drupal_add_js($path.'/theme/js/ext/jquery.ztree.core.js');
    drupal_add_js($path.'/theme/js/ext/jquery.ztree.excheck.js');
    drupal_add_js($path.'/theme/js/ext/jquery.ztree.exedit.js');
    drupal_add_js($path.'/theme/js/ext/jquery.ztree.exhide.js');
    drupal_add_js($path.'/theme/js/ext/fuzzysearch.js');
    drupal_add_js($path.'/theme/js/zmap_genotype_form.js');
    drupal_add_js($path.'/theme/js/jquery-ui.min.js');
    drupal_add_js($path.'/theme/js/tabulator.min.js');
    drupal_add_js($path.'/theme/js/zmap_genotype_search_result.js');

    return theme('zmap_genotype_search_result', array('dataset' => $dataset, 'germplasm' => $germplasms, 'chr' => $chr, 'start'=> $start, 'end' => $end));
}

/**
 * Implements hook_theme.
 */
function zmap_genotype_theme()
{
    $path = drupal_get_path('module', 'zmap_genotype');
    $theme = array(
        'zmap_genotype_search' => array(
            'variables' => array('type' => null),
            'template' => 'zmap_genotype_search',
            'path' => "$path/theme",
        ),
        'zmap_genotype_search_result' => array(
            'template' => 'zmap_genotype_search_result',
            'path' => "$path/theme",
        ),
    );

    return $theme;
}

/**
 * download search result tsv file.
 */
function zmap_genotype_search_result_downloadtsv($filename)
{
    $files_dir = variable_get('file_public_path', conf_path().'/files');
    $path = $files_dir.'/zmap_genotype_search_result/'.$filename;
    $file_size = filesize($path);
    $buffer = 1024;
    $count = 0;
    if (file_exists($path)) {
        header('Content-type:application/octet-stream');
        header('Accept-Ranges:bytes');
        header("Accept-Length:$file_size");
        header('Content-Disposition:attachment;filename='.$filename);
        $fp = fopen($path, 'r');
        while (!feof($fp) && $count < $file_size) {
            $contents = fread($fp, $buffer);
            $count += $buffer;
            echo $contents;
        }
        fclose($fp);
    } else {
        drupal_not_found();
    }
}
